#' @title Class CoutQc
#'
#' @description
#' The \code{CoutQc} class facilitates the counting of medical resource use
#' across individuals. Using databases structured by the [coutqc_bd()] function,
#' it features processes to convert resource utilization data, calculate
#' inflated costs at a reference year, and produce both an aggregated database
#' and a summary of average actual costs.
#'
#' @seealso
#' [coutqc_bd()], [data_aggregate()]
#'
#' vignette("Introduction_macro_CoutsQc", package = "CoutsQc")
#'
#' @importFrom R6 R6Class
#' @importFrom purrr map_vec map iwalk map2 keep
#' @importFrom data.table fwrite data.table
#' @importFrom collapse all_identical ftransformv join get_vars funique setv ss
#' @importFrom collapse vec fmatch unlist2d qF collapv fsum pivot ftransform
#' @importFrom collapse add_vars na_rm whichNA whichv alloc setop
#' @importFrom collapse as_integer_factor
#'
#' @rdname class-CoutQc
#' @export
CoutQc <- R6::R6Class(
	"CoutQc",
	cloneable = FALSE,
	public = list(
		#' @description
		#' Creating a new \code{CoutQc} object.
		#'
		#' @param ... Pairs \code{<name> = <CoutQc_bd>}, a database object of
		#'  class \code{CoutQc_bd}. See [coutqc_bd()] for specification on the database
		#'  object. The given `<name>` helps to identify the database in the function
		#'  output.
		#' @param cohort A \code{data.frame} of the cohort database.
		#' @param public_insurance A \code{data.frame} of individual's eligibility to
		#'  Quebec public insurance plan.
		#' @param alive \code{logical}. If \code{TRUE}, compute if an individual is
		#'  alive or dead at each periods.
		#' @param eligible \code{logical}. IF \code{TRUE}, compute if an individual is
		#'  covered or not by the Quebec public drug insurance plan at each periods.
		#' @param filter_index \code{logical}. If \code{TRUE}, exclude services
		#'  administered before an index date.
		#' @param filter_cohort_id \code{logical}. If \code{TRUE}, retaining only
		#'  individuals whose unique identifier `id` is present in the cohort database.
		#' @param filter_period_limit A vector of length 2 for the minimum and maximum
		#'  periods. It allows to specify a range of periods to keep. Values must be in
		#'  the range of those computed by the `coutqc_bd` period to work properly and
		#'  may change according to the `period_duration` argument. By default
		#'  \code{NULL}, keeps all observed periods.
		#' @param analysis \code{logical}; \code{TRUE}, performs analyses of augmented
		#'  databases. \code{FALSE}, to prevent analyses.
		#' @param by_aggregate A vector of column names used in the data aggregation.
		#'  By default \code{c("database", "period")}, aggregates actual costs by
		#'  \code{period} (generated by \code{CoutQc_bd}) and \code{database}(the name
		#'  of the database).
		#'
		#' @return A \code{CoutQc} class object.
		initialize = function(
		...,
		cohort = NULL,
		public_insurance = NULL,
		alive = FALSE,
		eligible = FALSE,
		filter_index = FALSE,
		filter_cohort_id = FALSE,
		filter_period_limit = NULL,
		analysis = TRUE,
		by_aggregate = NULL
		) {
			# Argument list_db ----
			list_db <- list(...)
			names(list_db) <- make.names(...names(), unique = TRUE)
			if (!all(purrr::map_vec(list_db, \(x) "CoutQc_bd" %in% class(x))))
				stop(paste(
					strwrap("The input database must be 'CoutQc_bd' class objects.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!collapse::all_identical(purrr::map(list_db, \(x) x$reference_year)))
				stop(paste(
					strwrap("The 'reference_year' argument must be the same in every
									database.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)
			if (!collapse::all_identical(purrr::map(list_db, \(x) x$period_duration)))
				stop(paste(
					strwrap("The 'period_duration' argument must be the same in every
									database.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)
			if (!collapse::all_identical(purrr::map(list_db, \(x) x$follow_interval)))
				stop(paste(
					strwrap("The 'follow_interval' argument must be the same in every
									database.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			# Argument filter_period_limit -----
			if (!is.null(filter_period_limit)){
				if (!is.numeric(filter_period_limit))
					stop(paste(
						strwrap("The 'filter_period_limit' argument must be 'numeric'.",
										prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!length(filter_period_limit) == 2)
					stop(paste(
						strwrap("The 'filter_period_limit' argument must be of length 2.",
										prefix = " "),
						collapse = "\n\t "), call. = FALSE)
			}

			# Argument logical ----
			if (!is.logical(alive))
				stop(paste(
					strwrap("The 'alive' argument must be 'logical'.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!length(alive) == 1)
				stop(paste(
					strwrap("The 'alive' argument must be of length 1.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (isTRUE(alive)) {
				if (is.null(cohort))
					stop(paste(
						strwrap("The 'cohort' database must be available to computes alive
										indicator.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!all(c("id", "date_birth", "date_death") %in% names(cohort)))
					stop(paste(
						strwrap("The 'cohort' database must contain the variables:\n\t
										'date_birth' and 'date_death'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!any(class(cohort[["date_birth"]]) %in% c("IDate", "Date")))
					stop(paste(
						strwrap("The 'cohort$date_birth' variable must be of class 'Date'.",
										prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!any(class(cohort[["date_death"]]) %in% c("IDate", "Date")))
					stop(paste(
						strwrap("The 'cohort$date_death' variable must be of class 'Date'.",
										prefix = " "),
						collapse = "\n\t "), call. = FALSE)
			}

			if (!is.logical(eligible))
				stop(paste(
					strwrap("The 'eligible' argument must be 'logical'.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!length(eligible) == 1)
				stop(paste(
					strwrap("The 'eligible' argument must be of length 1.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (isTRUE(eligible)) {
				if (is.null(public_insurance))
					stop(paste(
						strwrap("The 'public_insurance' database must be available to
										computes RAMQ eligiblility indicator.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!all(
					c("id", "date_subscribe", "date_withdraw") %in% names(public_insurance)
				))
					stop(paste(
						strwrap("The 'public_insurance' database must contain the variables:\n\t
										'date_subscribe' and 'date_withdraw'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!any(
					class(public_insurance[["date_subscribe"]]) %in% c("IDate", "Date")
				))
					stop(paste(
						strwrap("The 'public_insurance$date_subscribe' variable must be of
										class 'Date'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!any(class(public_insurance[["date_withdraw"]]) %in% c("IDate", "Date")))
					stop(paste(
						strwrap("The 'public_insurance$date_withdraw' variable must be of
										class 'Date'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)
			}

			if (!is.logical(filter_index))
				stop(paste(
					strwrap("The 'filter_index' argument must be 'logical'.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!length(filter_index) == 1)
				stop(paste(
					strwrap("The 'filter_index' argument must be of length 1.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (isTRUE(filter_index)) {
				if (is.null(cohort))
					stop(paste(
						strwrap("The 'cohort' database must be available to filter services
										to index date.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!all(c("id", "date_index") %in% names(cohort)))
					stop(paste(
						strwrap("The 'cohort' database must contain the variables:\n\t
										'id' and 'date_index'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!any(class(cohort[["date_index"]]) %in% c("IDate", "Date")))
					stop(paste(
						strwrap("The 'cohort$date_index' variable must be of class 'Date'.",
										prefix = " "),
						collapse = "\n\t "), call. = FALSE)
			}

			if (!is.logical(filter_cohort_id))
				stop(paste(
					strwrap("The 'filter_cohort_id' argument must be 'logical'.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!length(filter_cohort_id) == 1)
				stop(paste(
					strwrap("The 'filter_cohort_id' argument must be of length 1.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (isTRUE(filter_cohort_id)) {
				if (is.null(cohort))
					stop(paste(
						strwrap("The 'cohort' database must be available to filter cohort
										id.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)

				if (!"id" %in% names(cohort))
					stop(paste(
						strwrap("The 'cohort' database must contain the variables:\n\t
										'id'.", prefix = " "),
						collapse = "\n\t "), call. = FALSE)
			}

			if (!is.logical(analysis))
				stop(paste(
					strwrap("The 'analysis' argument must be 'logical'.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			if (!length(analysis) == 1)
				stop(paste(
					strwrap("The 'analysis' argument must be of length 1.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)

			# Argument by_aggregate ----
			if (is.null(by_aggregate)) {
				by_aggregate <- c("database", "period")
				if (length(list_db) == 1) {
					by_aggregate <- "period"
				}
			} else if (!is.character(by_aggregate)) {
				stop(paste(
					strwrap("The 'by_aggregate' argument must be a 'character'.",
									prefix = " "),
					collapse = "\n\t "), call. = FALSE)
			}

			# Arguments ----
			private$.list_db <- list_db
			private$.reference_year <- list_db[[1]]$reference_year
			private$.period_duration <- list_db[[1]]$period_duration
			private$.follow_interval <- list_db[[1]]$follow_interval
			private$.filter_period_limit <- filter_period_limit
			private$.cohort <- cohort
			private$.public_insurance <- public_insurance
			private$.options <- list(
				alive = alive,
				eligible = eligible,
				filter_index = filter_index,
				filter_cohort_id = filter_cohort_id,
				analysis = analysis
			)
			private$.by_aggregate <- by_aggregate
			private$.compute_indicator()
			private$.prep_aug_data()
			if (isTRUE(analysis)) {
				private$.validate_by_aggregate()
				private$.compute_analysis()
			}
		},

		#' @description
		#' Print information of an \code{CoutQc} object.
		#'
		#' @param ... Further arguments passed to or from other methods.
		#'
		print = function(...) {
			cat("Number of database:", length(self$aug_data), "\n")
			cat(paste0(
				"    ", names(self$aug_data), " ",
				purrr::map(self$aug_data, NROW), " obs.\n"),
				sep = "")
			cat(paste0(
				"Period duration: ", self$period_duration,
				if (self$period_duration == "follow") {
					paste(", with follow-up interval of",
								self$follow_interval, "days")
				},"\n"
			))
			cat("Reference year:", self$reference_year, "\n")
			if (!is.null(self$filter_period_limit)) {
				cat("Period limits: [",
						paste(self$filter_period_limit, collapse = ", "),
						"]\n", sep = "")
			}
			if (isTRUE(self$options[["analysis"]])) {
				cat("Aggregation by:", self$by_aggregate, "\n")
			}
			cat(
				"Options:\n",
				paste0(
					"    ",
					paste(names(self$options), self$options, sep = " = "),
					"\n"
				)
			)
			invisible(self)
		},

		#' @description
		#' Brief summary of results.
		#'
		#' @param ... Further arguments passed to or from other methods.
		#'
		summary = function(...) {
			cat(paste("Cost data were actualise to $CAD of",
								self$reference_year), "\n")
			cat("------------------------------------------------------------\n")
			if (!isTRUE(self$options[["analysis"]])) {
				cat("No analysis were performed.\n")
			} else {
				cat("Summary of actual costs\n")
				purrr::iwalk(
					self$data_summary,
					function(x, idx) {
						cat("$", idx, "\n", sep = "")
						print(collapse::ftransformv(
							x,
							vars = c("sum",
											 "mean_per_id",
											 "mean_per_id_greater_zero",
											 "proportion_id_greater_zero"),
							\(value) format(round(value, 2), nsmall = 2),
							apply = TRUE
						), ...)
					}
				)
				cat("------------------------------------------------------------\n")
				cat("Output cohort", NROW(self$out_cohort), "obs.\n")
				print(head(self$out_cohort, 9), ...)
				cat("...\n")
			}
			invisible(
				list(data_summary = self$data_summary, out_cohort = self$out_cohort)
			)
		},

		#' @description
		#' Exports augmented databases to .csv files. The file names correspond to
		#' the database names provided to the function, followed by
		#' "_augmented.csv".
		#'
		#' @param path Name of the folder to which the files will be exported.
		#' @param ... Further arguments passed to [data.table::fwrite()].
		#'
		write = function(path, ...) {
			if (!is.character(path))
				stop("The 'path' argument must be a charater string.",
						 call. = FALSE)
			purrr::iwalk(
				self$aug_data,
				function(dat, name) {
					data.table::fwrite(
						dat,
						file = paste0(path, "/", name, "_augmented.csv"),
						...
					)
				}
			)
			if (length(self$out_cohort) != 0) {
				data.table::fwrite(
					self$out_cohort,
					file = paste0(path, "/out_cohort.csv"),
					...
				)
			}
			cat(paste0("Augmented databases exported.\n"))
			invisible(self)
		}
	),
	private = list(
		.list_db = list(),
		.aug_data = list(),
		.reference_year = NA_integer_,
		.period_duration = NA_character_,
		.follow_interval = NA_integer_,
		.filter_period_limit = NA_integer_,
		.cohort = list(),
		.public_insurance = list(),
		.options = list(
			alive = FALSE,
			eligible = FALSE,
			filter_index = FALSE,
			filter_cohort_id = FALSE,
			analysis = TRUE
		),
		.out_cohort = list(),
		.data_summary = list(),
		.indicator = list(),
		.by_aggregate = NULL,

		.validate_by_aggregate = function() {
			# validate availability of variable in by_aggregate
			vars <- private$.by_aggregate
			vars_check <- vars[collapse::whichv(vars, "database", invert = TRUE)]
			purrr::iwalk(
				private$.aug_data,
				function(dt, indx) {
					var_miss <- vars_check[which(!vars_check %in% names(dt))]
					if (length(var_miss) != 0) {
						warn <- strwrap(paste(
							paste0(var_miss, collapse = ", "),
							"missing from", indx, "database"
						), prefix = " ")
						warning(paste(warn,	collapse = "\n\t "), call. = FALSE)
					}
				}
			)
			invisible(self)
		},

		.prep_aug_data = function() {
			aug_data <- purrr::map(
				private$.list_db,
				function(x) {
					private$.filter_data(x$aug_data) |>
						private$.merge_indicator()
				}
			) |>
				purrr::keep(\(x) nrow(x) != 0)
			if (length(aug_data)==0)
				stop(paste(
					strwrap("The filter options are too strict. No data remaining.", prefix = " "),
					collapse = "\n\t "), call. = FALSE)
			private$.aug_data <- aug_data
			invisible(self)
		},

		.merge_indicator = function(data) {
			for (i in seq_along(private$.indicator)) {
				data <- collapse::join(
					data,
					private$.indicator[[i]],
					on = c("id", "period"),
					drop.dup.cols = "x",
					verbose = FALSE
				)
			}
			data
		},

		.compute_indicator = function() {
			if (isTRUE(private$.options[["alive"]])) private$.alive()
			if (isTRUE(private$.options[["eligible"]])) private$.eligible()
			invisible(self)
		},

		.alive = function() {
			period_alive <- purrr::map(
				collapse::get_vars(private$.cohort, c("date_birth", "date_death")),
				function(date) {
					get_period(
						date = date,
						period_duration = private$.period_duration,
						index_date = private$.cohort[["date_index"]],
						follow_interval = private$.follow_interval
					)
				}
			)
			seq_period <- purrr::map(self$period, collapse::funique) |>
				unlist() |>
				collapse::na_rm() |>
				collapse::funique(sort = TRUE)

			# missing value in date_birth and date_death taken as alive
			collapse::setv(period_alive[["date_birth"]], NA, min(seq_period))
			collapse::setv(period_alive[["date_death"]], NA, max(seq_period))

			alive <- purrr::map2(
				period_alive[["date_birth"]],
				period_alive[["date_death"]],
				function(birth, death) {
					(birth <= seq_period) * (seq_period <= death)
				}
			) |> collapse::vec()
			private$.indicator[["alive"]] <- data.table::data.table(
				id = rep(private$.cohort[["id"]], each = length(seq_period)),
				period = rep(seq_period, length(private$.cohort[["id"]])),
				alive = alive
			)
			invisible(self)
		},

		.eligible = function() {
			if (private$.period_duration == "follow") {
				private$.public_insurance[["date_index"]] <-
					private$.cohort[["date_index"]][
					collapse::fmatch(
						private$.public_insurance[["id"]],
						private$.cohort[["id"]]
					)
				]
			}

			period_assurer <- purrr::map(
				collapse::get_vars(
					private$.public_insurance,
					c("date_subscribe", "date_withdraw")
				),
				function(date) {
					get_period(
						date = date,
						period_duration = private$.period_duration,
						index_date = private$.public_insurance[["date_index"]],
						follow_interval = private$.follow_interval
					)
				}
			)
			nb_na <-
				length(collapse::whichNA(period_assurer[["date_subscribe"]])) +
				length(collapse::whichNA(period_assurer[["date_withdraw"]]))

			if (!nb_na == 0)
				warning(paste(
					strwrap("In eligibility indicator: Missing values from
					'date_subscribe' and 'date_withdraw' where omited", prefix = " ")
				), call. = FALSE)

			seq_period <- purrr::map(self$period, collapse::funique) |>
				unlist() |>
				collapse::na_rm() |>
				collapse::funique(sort = TRUE)

			insured <- purrr::map2(
				period_assurer[["date_subscribe"]],
				period_assurer[["date_withdraw"]],
				function(x, y) {
					(x <= seq_period) * (seq_period <= y)
				}
			) |> collapse::unlist2d(idcols = FALSE, DT = TRUE)
			names(insured) <- as.character(seq_period)
			insured[["id"]] <- collapse::qF(private$.public_insurance[["id"]])
			insured <- collapse::collapv(insured, by = "id", FUN = collapse::fsum) |>
				collapse::pivot(ids = "id", names = list("period", "eligible")) |>
				collapse::ftransform(eligible = as.numeric(eligible > 0))
			private$.indicator[["eligible"]] <- data.table::data.table(
				id = collapse::as_integer_factor(insured$id),
				period = collapse::as_integer_factor(insured$period),
				insured = as.integer(insured$eligible)
			)
			invisible(self)
		},

		.filter_data = function(data) {
			index <- collapse::alloc(1, length(data[["id"]]))
			if (!is.null(private$.filter_period_limit)) {
				collapse::setop(
					index, "*",
					as.numeric(
						data[["period"]] >= private$.filter_period_limit[1] &
							data[["period"]] <= private$.filter_period_limit[2]
					)
				)
			}
			if (isTRUE(private$.options[["filter_cohort_id"]])) {
				collapse::setop(
					index, "*",
					as.numeric(
						!is.na(collapse::fmatch(
							data[["id"]], private$.cohort[["id"]], overid = 2L
						))
					)
				)
			}
			if (isTRUE(private$.options[["filter_index"]])) {
				if (!"date_index" %in% names(data)) {
					data <- collapse::add_vars(
						data,
						date_index = private$.cohort[["date_index"]][
							collapse::fmatch(data[["id"]], private$.cohort[["id"]])]
					)
				}
				collapse::setop(
					index, "*",
					as.numeric(data[["service_date"]] >= data[["date_index"]])
				)
			}
			collapse::ss(data, collapse::whichv(index, TRUE))
		},

		.compute_analysis = function() {
			out_cohort <- data_aggregate(
				aug_data = private$.aug_data,
				y = "actual_cost",
				by = private$.by_aggregate,
				expand = TRUE
			)

			if ("period" %in% names(out_cohort)) {
				out_cohort <- private$.merge_indicator(out_cohort)
			}
			data_summary <- data_summary(
				out_cohort,
				y = "actual_cost",
				by = private$.by_aggregate
			)
			private$.out_cohort <- out_cohort
			private$.data_summary <- data_summary
			invisible(self)
		},

		finalize = function() {}
	),
	active = list(
		#' @field unit_cost
		#' Accessor for the list of unit cost conversion tables.
		#'
		unit_cost = function(value) {
			if (missing(value)) {
				purrr::map(private$.list_db,\(x) x$unit_cost)
			} else {
				stop("$unit_cost is read only.", call. = FALSE)
			}
		},

		#' @field cpi
		#' Accessor for the Consumer price index conversion table.
		#'
		cpi = function(value) {
			if (missing(value)) {
				purrr::map(private$.list_db,\(x) x$cpi)
			} else {
				stop("$cpi is read only.", call. = FALSE)
			}
		},

		#' @field reference_year
		#' Accessor for reference_year attribute.
		#'
		reference_year = function(value) {
			if (missing(value)) {
				private$.reference_year
			} else {
				stop("$reference_year is read only.", call. = FALSE)
			}
		},

		#' @field period_duration
		#' Accessor for period_duration attribute.
		#'
		period_duration = function(value) {
			if (missing(value)) {
				private$.period_duration
			} else {
				stop("$period_duration is read only.", call. = FALSE)
			}
		},

		#' @field follow_interval
		#' Accessor for follow_interval attribute.
		#'
		follow_interval = function(value) {
			if (missing(value)) {
				private$.follow_interval
			} else {
				stop("$follow_interval is read only.", call. = FALSE)
			}
		},

		#' @field filter_period_limit
		#' Accessor for filter_period_limit attribute.
		#'
		filter_period_limit = function(value) {
			if (missing(value)) {
				private$.filter_period_limit
			} else {
				stop("$filter_period_limit is read only.", call. = FALSE)
			}
		},

		#' @field cohort
		#' Accessor for cohort database.
		#'
		cohort = function(value) {
			if (missing(value)) {
				private$.cohort
			} else {
				stop("$cohort is read only", call. = FALSE)
			}
		},

		#' @field public_insurance
		#' Accessor for public insurance database.
		#'
		public_insurance = function(value) {
			if (missing(value)) {
				private$.public_insurance
			} else {
				stop("$public_insurance is read only.", call. = FALSE)
			}
		},

		#' @field options
		#' Accessor for coutsqc options.
		#'
		options = function(value) {
			if (missing(value)) {
				private$.options
			} else {
				stop("$options is read only.", call. = FALSE)
			}
		},

		#' @field aug_data
		#' Accessor for augmented databases.
		#'
		aug_data = function(value) {
			if (missing(value)) {
				private$.aug_data
			} else {
				stop("$aug_data is read only", call. = FALSE)
			}
		},

		#' @field period
		#' Accessor for period attribute.
		#'
		period = function(value) {
			if (missing(value)) {
				purrr::map(private$.list_db,\(x) x$period)
			} else {
				stop("$period is read only", call. = FALSE)
			}
		},

		#' @field nominal_cost
		#' Accessor for nominal costs list.
		#'
		nominal_cost = function(value) {
			if (missing(value)) {
				purrr::map(private$.list_db,\(x) x$nominal_cost)
			} else {
				stop("$nominal_cost is read only", call. = FALSE)
			}
		},

		#' @field actual_cost
		#' Accessor for actual costs list.
		#'
		actual_cost = function(value) {
			if (missing(value)) {
				purrr::map(private$.list_db,\(x) x$actual_cost)
			} else {
				stop("$actual_cost is read only", call. = FALSE)
			}
		},

		#' @field indicator
		#' Accessor for indicator list.
		#'
		indicator = function(value) {
			if (missing(value)) {
				private$.indicator
			} else {
				stop("$indicator is read only", call. = FALSE)
			}
		},

		#' @field by_aggregate
		#' Accessor for by_aggregate.
		#'
		by_aggregate = function(value) {
			if (missing(value)) {
				private$.by_aggregate
			} else {
				stop("$by_aggregate is read only.", call. = FALSE)
			}
		},

		#' @field out_cohort
		#' Accessor for output cohort.
		#'
		out_cohort = function(value) {
			if (missing(value)) {
				private$.out_cohort
			} else {
				stop("$out_cohort is read only", call. = FALSE)
			}
		},

		#' @field data_summary
		#' Accessor for data_summary attribute.
		#'
		data_summary = function(value) {
			if (missing(value)) {
				private$.data_summary
			} else {
				stop("$data_summary is read only", call. = FALSE)
			}
		}
	)
)
