#' @title Macro CoutQc
#'
#' @description
#' The \code{coutqc()} function allows to instance a [CoutQc] object with a set
#' of Quebec medico-administrative databases.
#'
#' The \code{CoutQc} class facilitates the counting of medical resource use
#' across individuals. Using databases structured by the [coutqc_bd()] function,
#' it features processes to convert resource utilization data, calculate
#' inflated costs at a reference year, and produce both an aggregated database
#' and a summary of average actual costs.
#'
#' @usage coutqc(..., cohort = NULL, public_insurance = NULL, alive = FALSE,
#'  eligible = FALSE, filter_index = FALSE, filter_cohort_id = FALSE,
#'  filter_period_limit = NULL, analysis = TRUE, by_aggregate = NULL)
#'
#' @param ... Pairs \code{<name> = <CoutQc_bd>}, a database object of
#'  class \code{CoutQc_bd}. See [coutqc_bd()] for specification on the database
#'  object. The given `<name>` helps to identify the database in the function
#'  output.
#' @param cohort A \code{data.frame} of the cohort database.
#' @param public_insurance A \code{data.frame} of individual's eligibility to
#'  Quebec public insurance plan.
#' @param alive \code{logical}. If \code{TRUE}, compute if an individual is
#'  alive or dead at each periods.
#' @param eligible \code{logical}. IF \code{TRUE}, compute if an individual is
#'  covered or not by the Quebec public drug insurance plan at each periods.
#' @param filter_index \code{logical}. If \code{TRUE}, exclude services
#'  administered before an index date.
#' @param filter_cohort_id \code{logical}. If \code{TRUE}, retaining only
#'  individuals whose unique identifier `id` is present in the cohort database.
#' @param filter_period_limit A vector of length 2 for the minimum and maximum
#'  periods. It allows to specify a range of periods to keep. Values must be in
#'  the range of those computed by the `coutqc_bd` period to work properly and
#'  may change according to the `period_duration` argument. By default
#'  \code{NULL}, keeps all observed periods.
#' @param analysis \code{logical}; \code{TRUE}, performs analyses of augmented
#'  databases. \code{FALSE}, to prevent analyses.
#' @param by_aggregate A vector of column names used in the data aggregation.
#'  By default \code{c("database", "period")}, aggregates actual costs by
#'  \code{period} (generated by \code{CoutQc_bd}) and \code{database}(the name
#'  of the database).
#'
#' @export
coutqc <- function(
		...,
		cohort = NULL,
		public_insurance = NULL,
		alive = FALSE,
		eligible = FALSE,
		filter_index = FALSE,
		filter_cohort_id = FALSE,
		filter_period_limit = NULL,
		analysis = TRUE,
		by_aggregate = NULL
) {
	call <- match.call()
	call[[1]] <- quote(CoutsQc::CoutQc$new)
	eval(call, parent.frame())
}





